/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OperationsRouteImport } from './routes/operations'
import { Route as ReportIssueRouteImport } from './routes/report-issue'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAuditLogsRouteImport } from './routes/admin.audit-logs'
import { Route as AdminSecurityRouteImport } from './routes/admin.security'
import { Route as AdminStoresRouteImport } from './routes/admin.stores'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as CasesIdRouteImport } from './routes/cases.$id'
import { Route as CustomerIndexRouteImport } from './routes/customer.index'
import { Route as CustomerChatRouteImport } from './routes/customer.chat'
import { Route as CustomerProfileRouteImport } from './routes/customer.profile'
import { Route as CustomerSupportRouteImport } from './routes/customer.support'
import { Route as DarkStoresIndexRouteImport } from './routes/dark-stores.index'
import { Route as ExecutiveIndexRouteImport } from './routes/executive.index'
import { Route as FraudIndexRouteImport } from './routes/fraud.index'
import { Route as FraudIdRouteImport } from './routes/fraud.$id'
import { Route as SimulatedUpstreamOrderConfirmationRouteImport } from './routes/simulated-upstream.order-confirmation'
import { Route as SupportIndexRouteImport } from './routes/support.index'
import { Route as SupportPerformanceRouteImport } from './routes/support.performance'
import { Route as AdminSecurityEventsRouteImport } from './routes/admin.security.events'
import { Route as AdminSecurityUserActivityRouteImport } from './routes/admin.security.user-activity'
import { Route as CustomerComplaintsIndexRouteImport } from './routes/customer.complaints.index'
import { Route as CustomerComplaintsIdRouteImport } from './routes/customer.complaints_.$id'
import { Route as CustomerOrdersIndexRouteImport } from './routes/customer.orders.index'
import { Route as CustomerOrdersIdRouteImport } from './routes/customer.orders_.$id'
import { Route as DarkStoresIdIndexRouteImport } from './routes/dark-stores.$id.index'
import { Route as DarkStoresIdPulseRouteImport } from './routes/dark-stores.$id.pulse'
import { Route as SupportTicketsIdRouteImport } from './routes/support.tickets.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OperationsRoute = OperationsRouteImport.update({
  id: '/operations',
  path: '/operations',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportIssueRoute = ReportIssueRouteImport.update({
  id: '/report-issue',
  path: '/report-issue',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuditLogsRoute = AdminAuditLogsRouteImport.update({
  id: '/admin/audit-logs',
  path: '/admin/audit-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSecurityRoute = AdminSecurityRouteImport.update({
  id: '/admin/security',
  path: '/admin/security',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminStoresRoute = AdminStoresRouteImport.update({
  id: '/admin/stores',
  path: '/admin/stores',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesIdRoute = CasesIdRouteImport.update({
  id: '/cases/$id',
  path: '/cases/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerIndexRoute = CustomerIndexRouteImport.update({
  id: '/customer/',
  path: '/customer/',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerChatRoute = CustomerChatRouteImport.update({
  id: '/customer/chat',
  path: '/customer/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerProfileRoute = CustomerProfileRouteImport.update({
  id: '/customer/profile',
  path: '/customer/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerSupportRoute = CustomerSupportRouteImport.update({
  id: '/customer/support',
  path: '/customer/support',
  getParentRoute: () => rootRouteImport,
} as any)
const DarkStoresIndexRoute = DarkStoresIndexRouteImport.update({
  id: '/dark-stores/',
  path: '/dark-stores/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExecutiveIndexRoute = ExecutiveIndexRouteImport.update({
  id: '/executive/',
  path: '/executive/',
  getParentRoute: () => rootRouteImport,
} as any)
const FraudIndexRoute = FraudIndexRouteImport.update({
  id: '/fraud/',
  path: '/fraud/',
  getParentRoute: () => rootRouteImport,
} as any)
const FraudIdRoute = FraudIdRouteImport.update({
  id: '/fraud/$id',
  path: '/fraud/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulatedUpstreamOrderConfirmationRoute =
  SimulatedUpstreamOrderConfirmationRouteImport.update({
    id: '/simulated-upstream/order-confirmation',
    path: '/simulated-upstream/order-confirmation',
    getParentRoute: () => rootRouteImport,
  } as any)
const SupportIndexRoute = SupportIndexRouteImport.update({
  id: '/support/',
  path: '/support/',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportPerformanceRoute = SupportPerformanceRouteImport.update({
  id: '/support/performance',
  path: '/support/performance',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSecurityEventsRoute = AdminSecurityEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AdminSecurityRoute,
} as any)
const AdminSecurityUserActivityRoute =
  AdminSecurityUserActivityRouteImport.update({
    id: '/user-activity',
    path: '/user-activity',
    getParentRoute: () => AdminSecurityRoute,
  } as any)
const CustomerComplaintsIndexRoute = CustomerComplaintsIndexRouteImport.update({
  id: '/customer/complaints/',
  path: '/customer/complaints/',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerComplaintsIdRoute = CustomerComplaintsIdRouteImport.update({
  id: '/customer/complaints_/$id',
  path: '/customer/complaints/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerOrdersIndexRoute = CustomerOrdersIndexRouteImport.update({
  id: '/customer/orders/',
  path: '/customer/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerOrdersIdRoute = CustomerOrdersIdRouteImport.update({
  id: '/customer/orders_/$id',
  path: '/customer/orders/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DarkStoresIdIndexRoute = DarkStoresIdIndexRouteImport.update({
  id: '/dark-stores/$id/',
  path: '/dark-stores/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const DarkStoresIdPulseRoute = DarkStoresIdPulseRouteImport.update({
  id: '/dark-stores/$id/pulse',
  path: '/dark-stores/$id/pulse',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportTicketsIdRoute = SupportTicketsIdRouteImport.update({
  id: '/support/tickets/$id',
  path: '/support/tickets/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/operations': typeof OperationsRoute
  '/report-issue': typeof ReportIssueRoute
  '/settings': typeof SettingsRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/security': typeof AdminSecurityRouteWithChildren
  '/admin/stores': typeof AdminStoresRoute
  '/admin/users': typeof AdminUsersRoute
  '/cases/$id': typeof CasesIdRoute
  '/customer/chat': typeof CustomerChatRoute
  '/customer/profile': typeof CustomerProfileRoute
  '/customer/support': typeof CustomerSupportRoute
  '/fraud/$id': typeof FraudIdRoute
  '/simulated-upstream/order-confirmation': typeof SimulatedUpstreamOrderConfirmationRoute
  '/support/performance': typeof SupportPerformanceRoute
  '/admin/': typeof AdminIndexRoute
  '/customer/': typeof CustomerIndexRoute
  '/dark-stores/': typeof DarkStoresIndexRoute
  '/executive/': typeof ExecutiveIndexRoute
  '/fraud/': typeof FraudIndexRoute
  '/support/': typeof SupportIndexRoute
  '/admin/security/events': typeof AdminSecurityEventsRoute
  '/admin/security/user-activity': typeof AdminSecurityUserActivityRoute
  '/customer/complaints/$id': typeof CustomerComplaintsIdRoute
  '/customer/orders/$id': typeof CustomerOrdersIdRoute
  '/dark-stores/$id/pulse': typeof DarkStoresIdPulseRoute
  '/support/tickets/$id': typeof SupportTicketsIdRoute
  '/customer/complaints/': typeof CustomerComplaintsIndexRoute
  '/customer/orders/': typeof CustomerOrdersIndexRoute
  '/dark-stores/$id/': typeof DarkStoresIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/operations': typeof OperationsRoute
  '/report-issue': typeof ReportIssueRoute
  '/settings': typeof SettingsRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/security': typeof AdminSecurityRouteWithChildren
  '/admin/stores': typeof AdminStoresRoute
  '/admin/users': typeof AdminUsersRoute
  '/cases/$id': typeof CasesIdRoute
  '/customer/chat': typeof CustomerChatRoute
  '/customer/profile': typeof CustomerProfileRoute
  '/customer/support': typeof CustomerSupportRoute
  '/fraud/$id': typeof FraudIdRoute
  '/simulated-upstream/order-confirmation': typeof SimulatedUpstreamOrderConfirmationRoute
  '/support/performance': typeof SupportPerformanceRoute
  '/admin': typeof AdminIndexRoute
  '/customer': typeof CustomerIndexRoute
  '/dark-stores': typeof DarkStoresIndexRoute
  '/executive': typeof ExecutiveIndexRoute
  '/fraud': typeof FraudIndexRoute
  '/support': typeof SupportIndexRoute
  '/admin/security/events': typeof AdminSecurityEventsRoute
  '/admin/security/user-activity': typeof AdminSecurityUserActivityRoute
  '/customer/complaints/$id': typeof CustomerComplaintsIdRoute
  '/customer/orders/$id': typeof CustomerOrdersIdRoute
  '/dark-stores/$id/pulse': typeof DarkStoresIdPulseRoute
  '/support/tickets/$id': typeof SupportTicketsIdRoute
  '/customer/complaints': typeof CustomerComplaintsIndexRoute
  '/customer/orders': typeof CustomerOrdersIndexRoute
  '/dark-stores/$id': typeof DarkStoresIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/operations': typeof OperationsRoute
  '/report-issue': typeof ReportIssueRoute
  '/settings': typeof SettingsRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/security': typeof AdminSecurityRouteWithChildren
  '/admin/stores': typeof AdminStoresRoute
  '/admin/users': typeof AdminUsersRoute
  '/cases/$id': typeof CasesIdRoute
  '/customer/chat': typeof CustomerChatRoute
  '/customer/profile': typeof CustomerProfileRoute
  '/customer/support': typeof CustomerSupportRoute
  '/fraud/$id': typeof FraudIdRoute
  '/simulated-upstream/order-confirmation': typeof SimulatedUpstreamOrderConfirmationRoute
  '/support/performance': typeof SupportPerformanceRoute
  '/admin/': typeof AdminIndexRoute
  '/customer/': typeof CustomerIndexRoute
  '/dark-stores/': typeof DarkStoresIndexRoute
  '/executive/': typeof ExecutiveIndexRoute
  '/fraud/': typeof FraudIndexRoute
  '/support/': typeof SupportIndexRoute
  '/admin/security/events': typeof AdminSecurityEventsRoute
  '/admin/security/user-activity': typeof AdminSecurityUserActivityRoute
  '/customer/complaints_/$id': typeof CustomerComplaintsIdRoute
  '/customer/orders_/$id': typeof CustomerOrdersIdRoute
  '/dark-stores/$id/pulse': typeof DarkStoresIdPulseRoute
  '/support/tickets/$id': typeof SupportTicketsIdRoute
  '/customer/complaints/': typeof CustomerComplaintsIndexRoute
  '/customer/orders/': typeof CustomerOrdersIndexRoute
  '/dark-stores/$id/': typeof DarkStoresIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/operations'
    | '/report-issue'
    | '/settings'
    | '/admin/audit-logs'
    | '/admin/security'
    | '/admin/stores'
    | '/admin/users'
    | '/cases/$id'
    | '/customer/chat'
    | '/customer/profile'
    | '/customer/support'
    | '/fraud/$id'
    | '/simulated-upstream/order-confirmation'
    | '/support/performance'
    | '/admin/'
    | '/customer/'
    | '/dark-stores/'
    | '/executive/'
    | '/fraud/'
    | '/support/'
    | '/admin/security/events'
    | '/admin/security/user-activity'
    | '/customer/complaints/$id'
    | '/customer/orders/$id'
    | '/dark-stores/$id/pulse'
    | '/support/tickets/$id'
    | '/customer/complaints/'
    | '/customer/orders/'
    | '/dark-stores/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/operations'
    | '/report-issue'
    | '/settings'
    | '/admin/audit-logs'
    | '/admin/security'
    | '/admin/stores'
    | '/admin/users'
    | '/cases/$id'
    | '/customer/chat'
    | '/customer/profile'
    | '/customer/support'
    | '/fraud/$id'
    | '/simulated-upstream/order-confirmation'
    | '/support/performance'
    | '/admin'
    | '/customer'
    | '/dark-stores'
    | '/executive'
    | '/fraud'
    | '/support'
    | '/admin/security/events'
    | '/admin/security/user-activity'
    | '/customer/complaints/$id'
    | '/customer/orders/$id'
    | '/dark-stores/$id/pulse'
    | '/support/tickets/$id'
    | '/customer/complaints'
    | '/customer/orders'
    | '/dark-stores/$id'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/operations'
    | '/report-issue'
    | '/settings'
    | '/admin/audit-logs'
    | '/admin/security'
    | '/admin/stores'
    | '/admin/users'
    | '/cases/$id'
    | '/customer/chat'
    | '/customer/profile'
    | '/customer/support'
    | '/fraud/$id'
    | '/simulated-upstream/order-confirmation'
    | '/support/performance'
    | '/admin/'
    | '/customer/'
    | '/dark-stores/'
    | '/executive/'
    | '/fraud/'
    | '/support/'
    | '/admin/security/events'
    | '/admin/security/user-activity'
    | '/customer/complaints_/$id'
    | '/customer/orders_/$id'
    | '/dark-stores/$id/pulse'
    | '/support/tickets/$id'
    | '/customer/complaints/'
    | '/customer/orders/'
    | '/dark-stores/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  OperationsRoute: typeof OperationsRoute
  ReportIssueRoute: typeof ReportIssueRoute
  SettingsRoute: typeof SettingsRoute
  AdminAuditLogsRoute: typeof AdminAuditLogsRoute
  AdminSecurityRoute: typeof AdminSecurityRouteWithChildren
  AdminStoresRoute: typeof AdminStoresRoute
  AdminUsersRoute: typeof AdminUsersRoute
  CasesIdRoute: typeof CasesIdRoute
  CustomerChatRoute: typeof CustomerChatRoute
  CustomerProfileRoute: typeof CustomerProfileRoute
  CustomerSupportRoute: typeof CustomerSupportRoute
  FraudIdRoute: typeof FraudIdRoute
  SimulatedUpstreamOrderConfirmationRoute: typeof SimulatedUpstreamOrderConfirmationRoute
  SupportPerformanceRoute: typeof SupportPerformanceRoute
  AdminIndexRoute: typeof AdminIndexRoute
  CustomerIndexRoute: typeof CustomerIndexRoute
  DarkStoresIndexRoute: typeof DarkStoresIndexRoute
  ExecutiveIndexRoute: typeof ExecutiveIndexRoute
  FraudIndexRoute: typeof FraudIndexRoute
  SupportIndexRoute: typeof SupportIndexRoute
  CustomerComplaintsIdRoute: typeof CustomerComplaintsIdRoute
  CustomerOrdersIdRoute: typeof CustomerOrdersIdRoute
  DarkStoresIdPulseRoute: typeof DarkStoresIdPulseRoute
  SupportTicketsIdRoute: typeof SupportTicketsIdRoute
  CustomerComplaintsIndexRoute: typeof CustomerComplaintsIndexRoute
  CustomerOrdersIndexRoute: typeof CustomerOrdersIndexRoute
  DarkStoresIdIndexRoute: typeof DarkStoresIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operations': {
      id: '/operations'
      path: '/operations'
      fullPath: '/operations'
      preLoaderRoute: typeof OperationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report-issue': {
      id: '/report-issue'
      path: '/report-issue'
      fullPath: '/report-issue'
      preLoaderRoute: typeof ReportIssueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/audit-logs': {
      id: '/admin/audit-logs'
      path: '/admin/audit-logs'
      fullPath: '/admin/audit-logs'
      preLoaderRoute: typeof AdminAuditLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/security': {
      id: '/admin/security'
      path: '/admin/security'
      fullPath: '/admin/security'
      preLoaderRoute: typeof AdminSecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/stores': {
      id: '/admin/stores'
      path: '/admin/stores'
      fullPath: '/admin/stores'
      preLoaderRoute: typeof AdminStoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases/$id': {
      id: '/cases/$id'
      path: '/cases/$id'
      fullPath: '/cases/$id'
      preLoaderRoute: typeof CasesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/': {
      id: '/customer/'
      path: '/customer'
      fullPath: '/customer/'
      preLoaderRoute: typeof CustomerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/chat': {
      id: '/customer/chat'
      path: '/customer/chat'
      fullPath: '/customer/chat'
      preLoaderRoute: typeof CustomerChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/profile': {
      id: '/customer/profile'
      path: '/customer/profile'
      fullPath: '/customer/profile'
      preLoaderRoute: typeof CustomerProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/support': {
      id: '/customer/support'
      path: '/customer/support'
      fullPath: '/customer/support'
      preLoaderRoute: typeof CustomerSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dark-stores/': {
      id: '/dark-stores/'
      path: '/dark-stores'
      fullPath: '/dark-stores/'
      preLoaderRoute: typeof DarkStoresIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/executive/': {
      id: '/executive/'
      path: '/executive'
      fullPath: '/executive/'
      preLoaderRoute: typeof ExecutiveIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fraud/': {
      id: '/fraud/'
      path: '/fraud'
      fullPath: '/fraud/'
      preLoaderRoute: typeof FraudIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fraud/$id': {
      id: '/fraud/$id'
      path: '/fraud/$id'
      fullPath: '/fraud/$id'
      preLoaderRoute: typeof FraudIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulated-upstream/order-confirmation': {
      id: '/simulated-upstream/order-confirmation'
      path: '/simulated-upstream/order-confirmation'
      fullPath: '/simulated-upstream/order-confirmation'
      preLoaderRoute: typeof SimulatedUpstreamOrderConfirmationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support/': {
      id: '/support/'
      path: '/support'
      fullPath: '/support/'
      preLoaderRoute: typeof SupportIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support/performance': {
      id: '/support/performance'
      path: '/support/performance'
      fullPath: '/support/performance'
      preLoaderRoute: typeof SupportPerformanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/security/events': {
      id: '/admin/security/events'
      path: '/events'
      fullPath: '/admin/security/events'
      preLoaderRoute: typeof AdminSecurityEventsRouteImport
      parentRoute: typeof AdminSecurityRoute
    }
    '/admin/security/user-activity': {
      id: '/admin/security/user-activity'
      path: '/user-activity'
      fullPath: '/admin/security/user-activity'
      preLoaderRoute: typeof AdminSecurityUserActivityRouteImport
      parentRoute: typeof AdminSecurityRoute
    }
    '/customer/complaints/': {
      id: '/customer/complaints/'
      path: '/customer/complaints'
      fullPath: '/customer/complaints/'
      preLoaderRoute: typeof CustomerComplaintsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/complaints_/$id': {
      id: '/customer/complaints_/$id'
      path: '/customer/complaints/$id'
      fullPath: '/customer/complaints/$id'
      preLoaderRoute: typeof CustomerComplaintsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/orders/': {
      id: '/customer/orders/'
      path: '/customer/orders'
      fullPath: '/customer/orders/'
      preLoaderRoute: typeof CustomerOrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/orders_/$id': {
      id: '/customer/orders_/$id'
      path: '/customer/orders/$id'
      fullPath: '/customer/orders/$id'
      preLoaderRoute: typeof CustomerOrdersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dark-stores/$id/': {
      id: '/dark-stores/$id/'
      path: '/dark-stores/$id'
      fullPath: '/dark-stores/$id/'
      preLoaderRoute: typeof DarkStoresIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dark-stores/$id/pulse': {
      id: '/dark-stores/$id/pulse'
      path: '/dark-stores/$id/pulse'
      fullPath: '/dark-stores/$id/pulse'
      preLoaderRoute: typeof DarkStoresIdPulseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support/tickets/$id': {
      id: '/support/tickets/$id'
      path: '/support/tickets/$id'
      fullPath: '/support/tickets/$id'
      preLoaderRoute: typeof SupportTicketsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminSecurityRouteChildren {
  AdminSecurityEventsRoute: typeof AdminSecurityEventsRoute
  AdminSecurityUserActivityRoute: typeof AdminSecurityUserActivityRoute
}

const AdminSecurityRouteChildren: AdminSecurityRouteChildren = {
  AdminSecurityEventsRoute: AdminSecurityEventsRoute,
  AdminSecurityUserActivityRoute: AdminSecurityUserActivityRoute,
}

const AdminSecurityRouteWithChildren = AdminSecurityRoute._addFileChildren(
  AdminSecurityRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  OperationsRoute: OperationsRoute,
  ReportIssueRoute: ReportIssueRoute,
  SettingsRoute: SettingsRoute,
  AdminAuditLogsRoute: AdminAuditLogsRoute,
  AdminSecurityRoute: AdminSecurityRouteWithChildren,
  AdminStoresRoute: AdminStoresRoute,
  AdminUsersRoute: AdminUsersRoute,
  CasesIdRoute: CasesIdRoute,
  CustomerChatRoute: CustomerChatRoute,
  CustomerProfileRoute: CustomerProfileRoute,
  CustomerSupportRoute: CustomerSupportRoute,
  FraudIdRoute: FraudIdRoute,
  SimulatedUpstreamOrderConfirmationRoute:
    SimulatedUpstreamOrderConfirmationRoute,
  SupportPerformanceRoute: SupportPerformanceRoute,
  AdminIndexRoute: AdminIndexRoute,
  CustomerIndexRoute: CustomerIndexRoute,
  DarkStoresIndexRoute: DarkStoresIndexRoute,
  ExecutiveIndexRoute: ExecutiveIndexRoute,
  FraudIndexRoute: FraudIndexRoute,
  SupportIndexRoute: SupportIndexRoute,
  CustomerComplaintsIdRoute: CustomerComplaintsIdRoute,
  CustomerOrdersIdRoute: CustomerOrdersIdRoute,
  DarkStoresIdPulseRoute: DarkStoresIdPulseRoute,
  SupportTicketsIdRoute: SupportTicketsIdRoute,
  CustomerComplaintsIndexRoute: CustomerComplaintsIndexRoute,
  CustomerOrdersIndexRoute: CustomerOrdersIndexRoute,
  DarkStoresIdIndexRoute: DarkStoresIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
