/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OperationsRouteImport } from './routes/operations'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAuditLogsRouteImport } from './routes/admin.audit-logs'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as CasesIdRouteImport } from './routes/cases.$id'
import { Route as CustomerIndexRouteImport } from './routes/customer.index'
import { Route as CustomerProfileRouteImport } from './routes/customer.profile'
import { Route as CustomerSupportRouteImport } from './routes/customer.support'
import { Route as DarkStoresIndexRouteImport } from './routes/dark-stores.index'
import { Route as ExecutiveIndexRouteImport } from './routes/executive.index'
import { Route as FraudIndexRouteImport } from './routes/fraud.index'
import { Route as FraudIdRouteImport } from './routes/fraud.$id'
import { Route as SupportIndexRouteImport } from './routes/support.index'
import { Route as DarkStoresIdIndexRouteImport } from './routes/dark-stores.$id.index'
import { Route as DarkStoresIdPulseRouteImport } from './routes/dark-stores.$id.pulse'
import { Route as SupportTicketsIdRouteImport } from './routes/support.tickets.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OperationsRoute = OperationsRouteImport.update({
  id: '/operations',
  path: '/operations',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuditLogsRoute = AdminAuditLogsRouteImport.update({
  id: '/admin/audit-logs',
  path: '/admin/audit-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesIdRoute = CasesIdRouteImport.update({
  id: '/cases/$id',
  path: '/cases/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerIndexRoute = CustomerIndexRouteImport.update({
  id: '/customer/',
  path: '/customer/',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerProfileRoute = CustomerProfileRouteImport.update({
  id: '/customer/profile',
  path: '/customer/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerSupportRoute = CustomerSupportRouteImport.update({
  id: '/customer/support',
  path: '/customer/support',
  getParentRoute: () => rootRouteImport,
} as any)
const DarkStoresIndexRoute = DarkStoresIndexRouteImport.update({
  id: '/dark-stores/',
  path: '/dark-stores/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExecutiveIndexRoute = ExecutiveIndexRouteImport.update({
  id: '/executive/',
  path: '/executive/',
  getParentRoute: () => rootRouteImport,
} as any)
const FraudIndexRoute = FraudIndexRouteImport.update({
  id: '/fraud/',
  path: '/fraud/',
  getParentRoute: () => rootRouteImport,
} as any)
const FraudIdRoute = FraudIdRouteImport.update({
  id: '/fraud/$id',
  path: '/fraud/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportIndexRoute = SupportIndexRouteImport.update({
  id: '/support/',
  path: '/support/',
  getParentRoute: () => rootRouteImport,
} as any)
const DarkStoresIdIndexRoute = DarkStoresIdIndexRouteImport.update({
  id: '/dark-stores/$id/',
  path: '/dark-stores/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const DarkStoresIdPulseRoute = DarkStoresIdPulseRouteImport.update({
  id: '/dark-stores/$id/pulse',
  path: '/dark-stores/$id/pulse',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportTicketsIdRoute = SupportTicketsIdRouteImport.update({
  id: '/support/tickets/$id',
  path: '/support/tickets/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/operations': typeof OperationsRoute
  '/settings': typeof SettingsRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/users': typeof AdminUsersRoute
  '/cases/$id': typeof CasesIdRoute
  '/customer/profile': typeof CustomerProfileRoute
  '/customer/support': typeof CustomerSupportRoute
  '/fraud/$id': typeof FraudIdRoute
  '/admin/': typeof AdminIndexRoute
  '/customer/': typeof CustomerIndexRoute
  '/dark-stores/': typeof DarkStoresIndexRoute
  '/executive/': typeof ExecutiveIndexRoute
  '/fraud/': typeof FraudIndexRoute
  '/support/': typeof SupportIndexRoute
  '/dark-stores/$id/pulse': typeof DarkStoresIdPulseRoute
  '/support/tickets/$id': typeof SupportTicketsIdRoute
  '/dark-stores/$id/': typeof DarkStoresIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/operations': typeof OperationsRoute
  '/settings': typeof SettingsRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/users': typeof AdminUsersRoute
  '/cases/$id': typeof CasesIdRoute
  '/customer/profile': typeof CustomerProfileRoute
  '/customer/support': typeof CustomerSupportRoute
  '/fraud/$id': typeof FraudIdRoute
  '/admin': typeof AdminIndexRoute
  '/customer': typeof CustomerIndexRoute
  '/dark-stores': typeof DarkStoresIndexRoute
  '/executive': typeof ExecutiveIndexRoute
  '/fraud': typeof FraudIndexRoute
  '/support': typeof SupportIndexRoute
  '/dark-stores/$id/pulse': typeof DarkStoresIdPulseRoute
  '/support/tickets/$id': typeof SupportTicketsIdRoute
  '/dark-stores/$id': typeof DarkStoresIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/operations': typeof OperationsRoute
  '/settings': typeof SettingsRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/users': typeof AdminUsersRoute
  '/cases/$id': typeof CasesIdRoute
  '/customer/profile': typeof CustomerProfileRoute
  '/customer/support': typeof CustomerSupportRoute
  '/fraud/$id': typeof FraudIdRoute
  '/admin/': typeof AdminIndexRoute
  '/customer/': typeof CustomerIndexRoute
  '/dark-stores/': typeof DarkStoresIndexRoute
  '/executive/': typeof ExecutiveIndexRoute
  '/fraud/': typeof FraudIndexRoute
  '/support/': typeof SupportIndexRoute
  '/dark-stores/$id/pulse': typeof DarkStoresIdPulseRoute
  '/support/tickets/$id': typeof SupportTicketsIdRoute
  '/dark-stores/$id/': typeof DarkStoresIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/operations'
    | '/settings'
    | '/admin/audit-logs'
    | '/admin/users'
    | '/cases/$id'
    | '/customer/profile'
    | '/customer/support'
    | '/fraud/$id'
    | '/admin/'
    | '/customer/'
    | '/dark-stores/'
    | '/executive/'
    | '/fraud/'
    | '/support/'
    | '/dark-stores/$id/pulse'
    | '/support/tickets/$id'
    | '/dark-stores/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/operations'
    | '/settings'
    | '/admin/audit-logs'
    | '/admin/users'
    | '/cases/$id'
    | '/customer/profile'
    | '/customer/support'
    | '/fraud/$id'
    | '/admin'
    | '/customer'
    | '/dark-stores'
    | '/executive'
    | '/fraud'
    | '/support'
    | '/dark-stores/$id/pulse'
    | '/support/tickets/$id'
    | '/dark-stores/$id'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/operations'
    | '/settings'
    | '/admin/audit-logs'
    | '/admin/users'
    | '/cases/$id'
    | '/customer/profile'
    | '/customer/support'
    | '/fraud/$id'
    | '/admin/'
    | '/customer/'
    | '/dark-stores/'
    | '/executive/'
    | '/fraud/'
    | '/support/'
    | '/dark-stores/$id/pulse'
    | '/support/tickets/$id'
    | '/dark-stores/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  OperationsRoute: typeof OperationsRoute
  SettingsRoute: typeof SettingsRoute
  AdminAuditLogsRoute: typeof AdminAuditLogsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  CasesIdRoute: typeof CasesIdRoute
  CustomerProfileRoute: typeof CustomerProfileRoute
  CustomerSupportRoute: typeof CustomerSupportRoute
  FraudIdRoute: typeof FraudIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
  CustomerIndexRoute: typeof CustomerIndexRoute
  DarkStoresIndexRoute: typeof DarkStoresIndexRoute
  ExecutiveIndexRoute: typeof ExecutiveIndexRoute
  FraudIndexRoute: typeof FraudIndexRoute
  SupportIndexRoute: typeof SupportIndexRoute
  DarkStoresIdPulseRoute: typeof DarkStoresIdPulseRoute
  SupportTicketsIdRoute: typeof SupportTicketsIdRoute
  DarkStoresIdIndexRoute: typeof DarkStoresIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operations': {
      id: '/operations'
      path: '/operations'
      fullPath: '/operations'
      preLoaderRoute: typeof OperationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/audit-logs': {
      id: '/admin/audit-logs'
      path: '/admin/audit-logs'
      fullPath: '/admin/audit-logs'
      preLoaderRoute: typeof AdminAuditLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases/$id': {
      id: '/cases/$id'
      path: '/cases/$id'
      fullPath: '/cases/$id'
      preLoaderRoute: typeof CasesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/': {
      id: '/customer/'
      path: '/customer'
      fullPath: '/customer/'
      preLoaderRoute: typeof CustomerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/profile': {
      id: '/customer/profile'
      path: '/customer/profile'
      fullPath: '/customer/profile'
      preLoaderRoute: typeof CustomerProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/support': {
      id: '/customer/support'
      path: '/customer/support'
      fullPath: '/customer/support'
      preLoaderRoute: typeof CustomerSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dark-stores/': {
      id: '/dark-stores/'
      path: '/dark-stores'
      fullPath: '/dark-stores/'
      preLoaderRoute: typeof DarkStoresIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/executive/': {
      id: '/executive/'
      path: '/executive'
      fullPath: '/executive/'
      preLoaderRoute: typeof ExecutiveIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fraud/': {
      id: '/fraud/'
      path: '/fraud'
      fullPath: '/fraud/'
      preLoaderRoute: typeof FraudIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fraud/$id': {
      id: '/fraud/$id'
      path: '/fraud/$id'
      fullPath: '/fraud/$id'
      preLoaderRoute: typeof FraudIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support/': {
      id: '/support/'
      path: '/support'
      fullPath: '/support/'
      preLoaderRoute: typeof SupportIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dark-stores/$id/': {
      id: '/dark-stores/$id/'
      path: '/dark-stores/$id'
      fullPath: '/dark-stores/$id/'
      preLoaderRoute: typeof DarkStoresIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dark-stores/$id/pulse': {
      id: '/dark-stores/$id/pulse'
      path: '/dark-stores/$id/pulse'
      fullPath: '/dark-stores/$id/pulse'
      preLoaderRoute: typeof DarkStoresIdPulseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support/tickets/$id': {
      id: '/support/tickets/$id'
      path: '/support/tickets/$id'
      fullPath: '/support/tickets/$id'
      preLoaderRoute: typeof SupportTicketsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  OperationsRoute: OperationsRoute,
  SettingsRoute: SettingsRoute,
  AdminAuditLogsRoute: AdminAuditLogsRoute,
  AdminUsersRoute: AdminUsersRoute,
  CasesIdRoute: CasesIdRoute,
  CustomerProfileRoute: CustomerProfileRoute,
  CustomerSupportRoute: CustomerSupportRoute,
  FraudIdRoute: FraudIdRoute,
  AdminIndexRoute: AdminIndexRoute,
  CustomerIndexRoute: CustomerIndexRoute,
  DarkStoresIndexRoute: DarkStoresIndexRoute,
  ExecutiveIndexRoute: ExecutiveIndexRoute,
  FraudIndexRoute: FraudIndexRoute,
  SupportIndexRoute: SupportIndexRoute,
  DarkStoresIdPulseRoute: DarkStoresIdPulseRoute,
  SupportTicketsIdRoute: SupportTicketsIdRoute,
  DarkStoresIdIndexRoute: DarkStoresIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
